---
- name: restart postgresql
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_restarted_state }}"
    sleep: 5

- name: restart prometheus-postgres
  become: true
  systemd:
    daemon_reload: true
    name: prometheus-postgres-exporter.service
    state: restarted
